export const driverIds = ['hamilton', 'heidfeld', 'rosberg', 'alonso', 'kovalainen', 'nakajima', 'bourdais', 'raikkonen',
    'kubica', 'glock', 'sato', 'piquet_jr', 'massa', 'coulthard', 'trulli', 'sutil', 'webber', 'button', 'davidson',
    'vettel', 'fisichella', 'barrichello', 'ralf_schumacher', 'liuzzi', 'wurz', 'speed', 'albers', 'markus_winkelhock',
    'yamamoto', 'michael_schumacher', 'montoya', 'klien', 'monteiro', 'ide', 'villeneuve', 'montagny', 'rosa', 'doornbos',
    'karthikeyan', 'friesacher', 'zonta', 'pizzonia', 'matta', 'panis', 'pantano', 'bruni', 'baumgartner', 'gene', 'frentzen',
    'verstappen', 'wilson', 'firman', 'kiesa', 'burti', 'alesi', 'irvine', 'hakkinen', 'marques', 'bernoldi', 'mazzacane',
    'enge', 'yoong', 'salo', 'diniz', 'herbert', 'mcnish', 'buemi', 'takagi', 'badoer', 'zanardi', 'damon_hill', 'sarrazin',
    'rosset', 'tuero', 'nakano', 'magnussen', 'berger', 'larini', 'katayama', 'sospiri', 'morbidelli', 'fontana', 'lamy',
    'brundle', 'montermini', 'lavaggi', 'blundell', 'suzuki', 'inoue', 'moreno', 'wendlinger', 'gachot', 'schiattarella',
    'martini', 'mansell', 'boullion', 'papis', 'deletraz', 'tarquini', 'comas', 'brabham', 'senna', 'bernard', 'fittipaldi',
    'alboreto', 'beretta', 'ratzenberger', 'belmondo', 'lehto', 'cesaris', 'gounon', 'alliot', 'adams', 'dalmas', 'noda',
    'lagorce', 'prost', 'warwick', 'patrese', 'barbazza', 'andretti', 'capelli', 'boutsen', 'apicella', 'naspetti', 'toshio_suzuki',
    'gugelmin', 'poele', 'grouillard', 'chiesa', 'modena', 'amati', 'caffi', 'bertaggia', 'mccarthy', 'lammers', 'piquet',
    'satoru_nakajima', 'pirro', 'johansson', 'bailey', 'chaves', 'bartels', 'hattori', 'nannini', 'schneider', 'barilla',
    'foitek', 'langes', 'gary_brabham', 'donnelly', 'giacomelli', 'alguersuari', 'grosjean', 'kobayashi', 'palmer', 'danner',
    'cheever', 'sala', 'ghinzani', 'weidler', 'raphanel', 'arnoux', 'joachim_winkelhock', 'larrauri', 'streiff', 'campos',
    'schlesser', 'fabre', 'fabi', 'forini', 'laffite', 'angelis', 'dumfries', 'tambay', 'surer', 'keke_rosberg', 'jones',
    'rothengatter', 'berg', 'manfred_winkelhock', 'lauda', 'hesnault', 'baldi', 'bellof', 'acheson', 'watson', 'cecotto',
    'gartner', 'corrado_fabi', 'thackwell', 'serra', 'sullivan', 'salazar', 'guerrero', 'boesel', 'jarier', 'villeneuve_sr',
    'reutemann', 'mass', 'borgudd', 'pironi', 'gilles_villeneuve', 'paletti', 'henton', 'daly', 'mario_andretti', 'villota',
    'lees', 'byrne', 'keegan', 'rebaque', 'gabbiani', 'cogan', 'guerra', 'stohr', 'zunino', 'londono', 'jabouille', 'francia',
    'depailler', 'scheckter', 'regazzoni', 'emerson_fittipaldi', 'kennedy', 'south', 'needell', 'desire_wilson', 'ertl',
    'brambilla', 'hunt', 'merzario', 'stuck', 'brancatelli', 'ickx', 'gaillard', 'ribeiro', 'peterson', 'lunger', 'ongais',
    'leoni', 'galica', 'stommelen', 'colombo', 'trimmer', 'binder', 'bleekemolen', 'gimax', 'rahal', 'pace', 'ian_scheckter',
    'pryce', 'hoffmann', 'zorzi', 'nilsson', 'perkins', 'hayje', 'neve', 'purley', 'andersson', 'dryver', 'oliver', 'kozarowitzky',
    'sutcliffe', 'edwards', 'mcguire', 'schuppan', 'heyer', 'pilette', 'ashley', 'kessel', 'takahashi', 'hoshino', 'takahara',
    'lombardi', 'evans', 'leclere', 'amon', 'zapico', 'pescarolo', 'nelleman', 'magee', 'wilds', 'pesenti_rossi', 'stuppacher',
    'brown', 'hasemi', 'donohue', 'hill', 'wilson_fittipaldi', 'tunmer', 'keizan', 'charlton', 'brise', 'wunderink', 'migault',
    'palm', 'lennep', 'fushida', 'nicholson', 'morgan', 'crawford', 'vonlanthen', 'hulme', 'hailwood', 'beltoise', 'ganley',
    'robarts', 'revson', 'driver', 'belso', 'redman', 'opel', 'schenken', 'larrousse', 'kinnunen', 'wisell', 'roos', 'dolhem',
    'gethin', 'bell', 'hobbs', 'quester', 'koinigg', 'facetti', 'wietzes', 'cevert', 'stewart', 'beuttler', 'galli', 'bueno',
    'follmer', 'adamich', 'pretorius', 'williamson', 'mcrae', 'marko', 'walker', 'roig', 'love', 'surtees', 'barber', 'brack',
    'posey', 'rodriguez', 'siffert', 'bonnier', 'mazet', 'jean', 'elford', 'moser', 'eaton', 'lovely', 'craft', 'Cannoc',
    'jack_brabham', 'miles', 'rindt', 'gavin', 'mclaren', 'courage', 'klerk', 'giunti', 'gurney', 'hahne', 'hutchison',
    'westbury', 'tingle', 'rooyen', 'attwood', 'pease', 'cordts', 'clark', 'spence', 'scarfiotti', 'bianchi', 'jo_schlesser',
    'widdows', 'ahrens', 'gardner', 'unser', 'solana', 'anderson', 'botha', 'bandini', 'ginther', 'parkes', 'irwin', 'ligier',
    'rees', 'hart', 'fisher', 'tom_jones', 'baghetti', 'williams', 'bondurant', 'arundell', 'vic_wilson', 'taylor', 'lawrence',
    'trevor_taylor', 'geki', 'phil_hill', 'ireland', 'bucknum', 'hawkins', 'prophet', 'maggs', 'blokdyk', 'lederle', 'serrurier',
    'niemann', 'pieterse', 'puzey', 'reed', 'clapham', 'blignaut', 'gregory', 'rhodes', 'raby', 'rollinson', 'gubby', 'mitter',
    'bussinello', 'vaccarella', 'bassi', 'trintignant', 'collomb', 'andre_pilette', 'beaufort', 'barth', 'cabral', 'hansgen',
    'sharp', 'mairesse', 'campbell - jones', 'burgess', 'settember', 'estefano', 'hall', 'parnell', 'kuhnke', 'ernesto_brambilla',
    'lippi', 'seiffert', 'abate', 'starrabba', 'broeker', 'ward', 'vos', 'dochnal', 'monarch', 'gasly', 'lewis', 'ricardo_rodriguez',
    'seidel', 'salvadori', 'pon', 'slotemaker', 'marsh', 'ashmore', 'schiller', 'davis', 'chamberlain', 'shelly', 'greene',
    'walter', 'prinoth', 'penske', 'schroeder', 'mayer', 'johnstone', 'harris', 'hocking', 'vyver', 'moss', 'trips', 'allison',
    'herrmann', 'brooks', 'may', 'henry_taylor', 'gendebien', 'scarlatti', 'naylor', 'bordeu', 'fairman', 'natili', 'monteverdi',
    'pirocchi', 'duke', 'thiele', 'boffa', 'ryan', 'ruby', 'ken_miles', 'menditeguy', 'larreta', 'gonzalez', 'bonomi', 'munaron',
    'schell', 'stacey', 'chimeri', 'creus', 'bristow', 'halford', 'daigh', 'reventlow', 'rathmann', 'goldsmith', 'branson',
    'thomson', 'johnson', 'veith', 'tingelstad', 'christie', 'amick', 'darter', 'homeier', 'hartley', 'stevenson', 'grim',
    'templeman', 'hurtubise', 'bryan', 'ruttman', 'sachs', 'freeland', 'bettenhausen', 'weiler', 'foyt', 'russo', 'boyd',
    'force', 'mcwithey', 'sutton', 'dick_rathmann', 'herman', 'dempsey_wilson', 'mike_taylor', 'flockhart', 'piper', 'cabianca',
    'drogo', 'gamble', 'owen', 'gould', 'drake', 'bueb', 'Changy', 'filippis', 'lucienbonnet', 'testut', 'behra', 'paul_russo',
    'daywalt', 'arnold', 'keller', 'flaherty', 'cheesbourg', 'ray_crawford', 'turner', 'weyant', 'larson', 'magill', 'shelby',
    'orey', 'fontes', 'ashdown', 'bill_moss', 'dennis_taylor', 'blanchard', 'tomaso', 'constantine', 'said', 'cade', 'musso',
    'hawthorn', 'fangio', 'godia', 'collins', 'kavanagh', 'gerini', 'kessler', 'emery', 'piotti', 'ecclestone', 'taramazzo',
    'chiron', 'lewis - evans', 'george_amick', 'reece', 'parsons', 'tolan', 'garrett', 'elisian', 'connor', 'jerry_unser',
    'bisch', 'goethals', 'gibson', 'la_caze', 'guelfi', 'picard', 'bridger', 'portago', 'perdisa', 'castellotti', 'simon',
    'leston', 'hanks', 'linden', 'teague', 'edmunds', 'agabashian', 'george', 'macdowel', 'mackay - fraser', 'gerard',
    'maglioli', 'england', 'landi', 'uria', 'ramos', 'bayol', 'manzon', 'rosier', 'sweikert', 'griffith', 'dinsmore', 'andrews',
    'frere', 'villoresi', 'scotti', 'chapman', 'titterington', 'scott_Brown', 'volonterio', 'milhoux', 'graffenried', 'taruffi',
    'farina', 'mieres', 'mantovani', 'bucci', 'iglesias', 'ascari', 'kling', 'birger', 'pollet', 'macklin', 'whiteaway',
    'davies', 'faulkner', 'niday', 'cross', 'vukovich', 'mcgrath', 'hoyt', 'claes', 'peter_walker', 'sparken', 'wharton',
    'mcalpine', 'marr', 'rolt', 'fitch', 'lucas', 'bira', 'marimon', 'loyer', 'daponte', 'nazaruk', 'crockett', 'ayulo',
    'armi', 'webb', 'duncan', 'mccoy', 'swaters', 'georges_berger', 'beauman', 'thorne', 'whitehouse', 'riseley_prichard',
    'reg_parnell', 'whitehead', 'brandon', 'alan_brown', 'nuckey', 'lang', 'helfrich', 'wacker', 'riu', 'galvez', 'john_barber',
    'bonetto', 'cruz', 'nalon', 'scarborough', 'holland', 'bob_scott', 'legat', 'cabantous', 'crook', 'jimmy_stewart',
    'ian_stewart', 'duncan_hamilton', 'klodwig', 'krause', 'karch', 'heeks', 'fitzau', 'adolff', 'bechem', 'bauer', 'hans_stuck',
    'loof', 'scherrer', 'terra', 'hirt', 'carini', 'fischer', 'ulmen', 'abecassis', 'george_connor', 'rigsby', 'james',
    'schindler', 'fonder', 'banks', 'mcdowell', 'miller', 'ball', 'tornaco', 'laurent', 'obrien', 'gaze', 'charrington',
    'comotti', 'etancelin', 'poore', 'thompson', 'downing', 'graham_whitehead', 'bianco', 'murray', 'cantoni', 'aston',
    'brudes', 'riess', 'niedermayr', 'klenk', 'balsa', 'schoeller', 'pietsch', 'peters', 'lof', 'flinterman', 'dusio',
    'crespo', 'rol', 'sanesi', 'guy_mairesse', 'louveau', 'wallard', 'forberg', 'rose', 'mackey', 'green', 'walt_brown',
    'hellings', 'levegh', 'chaboud', 'gordini', 'kelly', 'parker', 'shawe_taylor', 'john_james', 'branca', 'richardson',
    'jover', 'grignard', 'hampshire', 'crossley', 'fagioli', 'harrison', 'fry', 'martin', 'leslie_johnson', 'biondetti',
    'pian', 'sommer', 'chitwood', 'fohr', 'ader', 'holmes', 'levrett', 'jackson', 'pagani', 'pozzi', 'serafini', 'cantrell',
    'mantz', 'kladis', 'oscar_gonzalez', 'hulkenberg', 'petrov', 'grassi', 'bruno_senna', 'chandhok', 'maldonado', 'resta',
    'perez', 'ambrosio', 'ricciardo', 'vergne', 'pic', 'chilton', 'gutierrez', 'bottas', 'garde', 'jules_bianchi', 'kevin_magnussen',
    'kvyat', 'lotterer', 'ericsson', 'stevens', 'max_verstappen', 'nasr', 'sainz', 'merhi', 'rossi', 'jolyon_palmer',
    'wehrlein', 'haryanto', 'vandoorne', 'ocon', 'stroll', 'giovinazzi', 'brendon_hartley', 'leclerc', 'sirotkin', 'norris',
    'russell', 'albon', 'latifi', 'pietro_fittipaldi', 'aitken', 'tsunoda', 'mazepin', 'mick_schumacher', 'zhou', 'de_vries',
    'piastri', 'sargeant'];